version: '3'
services: 
  web:
    container_name: node
    restart: always
    build: .
    ports: 
      - '80:3000'
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'    